### PR TITLE
Add LICENSE

### LINKED ISSUE #2: Needs a LICENSE
Needs to have a license added. Not sure if there is an expectation for what license to use for pocoo projects.

### PR DESCRIPTION
**Pull request by keyan**
Not sure who we want to have as author/org but Pallets made the most sense to me.

Fixes #2

### CODE REVIEW

**Comment by untitaker** [comment]
I wonder if this would be better released [under the public domain?](https://unlicense.org/) This basically means that not even the copyright notice needs to be preserved.

**Comment by keyan** [comment]
I'm not opposed. First time I've seen that to be honest.

**Comment by untitaker** [comment]
It's up to you since you wrote the thing. You can choose any license you like (strong preference for it to be MIT, BSD or public domain) and also change the copyright to your name if you want to.

**Comment by keyan** [comment]
Updated the copyright holder to be myself and kept the BSD license.

**Pull request merged**
